In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# --- Numpy ---

# Array

In [2]:
myList = list(range(10,100,10))

In [3]:
print(myList)
type(myList)

[10, 20, 30, 40, 50, 60, 70, 80, 90]


list

In [4]:
myListNp = np.array(myList)

In [5]:
print(myListNp)
type(myListNp)

[10 20 30 40 50 60 70 80 90]


numpy.ndarray

In [6]:
matrixListe = np.array([myList,myList,myList])

In [7]:
matrixListe

array([[10, 20, 30, 40, 50, 60, 70, 80, 90],
       [10, 20, 30, 40, 50, 60, 70, 80, 90],
       [10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [8]:
matrixListe[0]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
matrixListe[0][1]

20

# Arange

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(10,0,-1).reshape(5,2)

array([[10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

# zeros-ones

In [13]:
np.zeros(20).reshape(5,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(20).reshape(5,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Linspace

In [15]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [16]:
np.linspace(0,100,15)##Esit aralıklar ile boler

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

# Eye

In [17]:
np.eye(6)#Identity matrix
#Kosegen 1 kalan matrix elemanları 0

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Random

In [18]:
np.random.randn(10)#Tek boyutlu

array([-0.19304191,  0.67343111, -0.53201192,  1.3367105 ,  1.48213545,
        0.57633724, -1.16824769, -3.21705216, -0.49612968, -2.21091345])

In [19]:
np.random.randn(5,5)#İki boyutlu

array([[-0.3572058 , -0.09856791,  0.42850155,  1.27772371,  0.13467724],
       [-0.73727179,  1.04923827,  0.95206462,  0.07103935,  0.60441903],
       [-0.19474476,  0.21834226,  0.25525098,  1.85252801, -1.13134674],
       [ 0.42456883, -1.07302079,  0.14410562, -0.33138799,  0.40700183],
       [-1.53048479, -0.92729044,  0.51549356,  0.40013265, -1.26133667]])

In [20]:
np.random.random(5)

array([0.19802946, 0.10015988, 0.74014261, 0.71987026, 0.60617377])

In [21]:
##Randn ile random arasındaki fark randn 2 parametre alabilir.
##Randn 2 boyutlu dizi oluşturabilri ancak random tek boyutludur.

In [22]:
np.random.randint(1,100,3)#Tam sayı üretir

array([15, 77, 64])

# Numpy Array Methods

In [23]:
array = np.random.randint(0,100,20)
array

array([53, 18, 75, 68, 55, 75,  4, 14, 54, 14, 52, 15, 39,  3, 53, 85, 42,
       44, 35, 50])

In [24]:
array.reshape(5,4)

array([[53, 18, 75, 68],
       [55, 75,  4, 14],
       [54, 14, 52, 15],
       [39,  3, 53, 85],
       [42, 44, 35, 50]])

In [25]:
array.max()

85

In [26]:
array.min()

3

In [27]:
array.mean()

42.4

In [28]:
array.std()

23.78949347926517

In [29]:
array.var()

565.94

In [30]:
array.ndim

1

In [31]:
array.size

20

In [32]:
array.shape

(20,)

In [33]:
array.argmin()

13

In [34]:
array.argmax()

15

# İndexing

In [35]:
array = np.arange(25)

In [36]:
array[5]

5

In [37]:
array[3:15]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
array[0:5] = 15

In [39]:
array

array([15, 15, 15, 15, 15,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
array = array[::-1]#reversing

In [41]:
array

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5, 15, 15, 15, 15, 15])

In [42]:
array2 = array[:]
array2[:] = 33
array2

array([33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33])

# Matrix

In [43]:
matrixArray = np.random.randint(0,100,25).reshape(5,5)
matrixArray

array([[68, 92, 23, 76,  8],
       [67, 71,  6, 56, 18],
       [42, 70, 67, 43, 81],
       [ 0, 90,  0, 27, 27],
       [45, 90, 58, 47,  7]])

In [44]:
matrixArray[0][1]

92

In [45]:
matrixArray[0,1]

92

In [46]:
matrixArray[0:,3]

array([76, 56, 43, 27, 47])

In [47]:
matrixArray[2:,2:]

array([[67, 43, 81],
       [ 0, 27, 27],
       [58, 47,  7]])

In [48]:
matrixArray[[0,1,3]]

array([[68, 92, 23, 76,  8],
       [67, 71,  6, 56, 18],
       [ 0, 90,  0, 27, 27]])

In [51]:
matrixArray[[0,2,4]]

array([[68, 92, 23, 76,  8],
       [42, 70, 67, 43, 81],
       [45, 90, 58, 47,  7]])

In [53]:
matrixArray[[0,1,3],[0,1,4]]

array([68, 71, 27])

# Operators

In [66]:
newArray = np.random.randint(0,100,20)
newArray

array([55, 94, 25, 78, 12, 20, 90, 66, 55, 43, 17,  4, 21, 20, 50,  3, 13,
       26, 24, 66])

In [67]:
newArray < 15 #result = boolean

array([False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False,  True,  True, False,
       False, False])

In [68]:
resultArray = newArray <15

In [69]:
newArray[resultArray]

array([12,  4,  3, 13])

In [70]:
newArray[newArray <50]

array([25, 12, 20, 43, 17,  4, 21, 20,  3, 13, 26, 24])

In [71]:
newArray2 = newArray + newArray

In [72]:
newArray2

array([110, 188,  50, 156,  24,  40, 180, 132, 110,  86,  34,   8,  42,
        40, 100,   6,  26,  52,  48, 132])

In [73]:
newArray/5

array([11. , 18.8,  5. , 15.6,  2.4,  4. , 18. , 13.2, 11. ,  8.6,  3.4,
        0.8,  4.2,  4. , 10. ,  0.6,  2.6,  5.2,  4.8, 13.2])

In [74]:
newArray - 100

array([-45,  -6, -75, -22, -88, -80, -10, -34, -45, -57, -83, -96, -79,
       -80, -50, -97, -87, -74, -76, -34])

In [76]:
np.sqrt(newArray)

array([7.41619849, 9.69535971, 5.        , 8.83176087, 3.46410162,
       4.47213595, 9.48683298, 8.1240384 , 7.41619849, 6.55743852,
       4.12310563, 2.        , 4.58257569, 4.47213595, 7.07106781,
       1.73205081, 3.60555128, 5.09901951, 4.89897949, 8.1240384 ])